name: gitea
services:
  anubis:
    image: ghcr.io/techarohq/anubis:v1.26.0-pre1
    container_name: anubis
    environment:
      BIND: ":8080"
      DIFFICULTY: "4"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://gitea:30000"
      POLICY_FNAME: "/data/cfg/botPolicy.yaml"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    ports:
      - 127.0.0.1:4005:8080
    volumes:
      - "./botPolicy.yaml:/data/cfg/botPolicy.yaml:ro"

  gitea:
    image: docker.gitea.com/gitea:1.26.4
    container_name: gitea
    env_file: .env
    restart: always
    volumes:
      - /nas/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "222:22"
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    container_name: gitea_postgres
    restart: always
    env_file: .env
    networks:
      - gitea
    volumes:
      - pg_data::/var/lib/postgresql/data

volumes:
  pg_data:
