services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vault.renoux.dev"
    volumes:
      - /nas/vaultwarden/vw-data/:/data/
    ports:
      - 127.0.0.1:4050:80
