name: jellyfin
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:10.11.11
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 127.0.0.1:4080:8096
    volumes:
      - /home/fantomitechno/jellyfin/config:/config
      - /home/fantomitechno/jellyfin/cache:/cache
      - /nas/media/tv:/data/tvshows
      - /nas/media/movies:/data/movies
      - /nas/downloads:/data/media_downloads
    restart: unless-stopped
