name: update-checker
services:
  update-checker:
    # Use my own custom update-checker image
    image: ghcr.io/fantomitechno/update-checker:latest
    container_name: update-checker
    volumes:
      # custom configurations
      - ./config.yml:/app/update_checker_config.yaml
      - /data/celeste/mods:/mods
      - /data/celeste/images:/images
      - /data/celeste/rich_presence:/rich_presences
    restart: unless-stopped

volumes:
  cnet_data:
