name: celeste-mirror
services:
  celeste-mirror:
    # Use my own custom celeste-mirror image
    image: ghcr.io/fantomitechno/celeste-mirror:latest
    container_name: celeste-mirror
    volumes:
      # custom configurations
      - ./config.toml:/app/config.toml
      - /data/celeste/mods:/mods
      - /data/celeste/images:/images
      - /data/celeste/rich_presence:/rich_presences
    restart: unless-stopped
